### ISSUE TITLE
Update react dependencies

### ISSUE THREAD

**Issue by esteban-url** [jon-sully/react-netlify-identity-gotrue#1]
Hey Jon,

Thanks for building this, i was in the process of building something similar, but just ran into this, so i thought i would give it a go.

Right of the bat, it was giving me problems because im on react 17, and using npm it would error out when installing. yarn manage it nicely tho. 

I've found some other issues, but wanted to know if there are any contributing rules I should be following.
I've already cloned the repo and started working on some other small fixes.

**Comment by jon-sully** [comment]
Greetings! React 17 has been added as a valid peer dependency version as of v0.3.4 😃 thanks for the heads up!
