### ISSUE TITLE
Error getting token ends up on JS error

### ISSUE THREAD

**Issue by zane-commeatio** [jon-sully/react-netlify-identity-gotrue#8]
I am frequently getting an error
![image](https://user-images.githubusercontent.com/36542885/127014668-f9689b51-b696-4bde-9db1-6ca7311873aa.png)
 always preceded by an identity API error
 
![image](https://user-images.githubusercontent.com/36542885/127014947-a361b7d2-add0-4549-9353-807d8efc11d4.png)

I am not managing the refresh token myself, so what could do that the resfresh token is invalid ?

**Comment by Zukqurnain** [comment]
I receiving the same error any solution?
